AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: The environment (e.g., dev, prod)
  GitHubRepo:
    Type: String
    Description: The GitHub repository URL
  GitHubBranch:
    Type: String
    Description: The GitHub branch to build
  ArtifactsBucket:
    Type: String
    Description: The S3 bucket for build artifacts
  CodeBuildRoleArn:
    Type: String
    Description: The ARN of the IAM role for CodeBuild
  ECRRepositoryURI:
    Type: String
    Description: The URI of the ECR repository
  GitHubAccessTokenSecretName:
    Type: String
    Description: The name of the secret containing the GitHub access token

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "codebuild-${Environment}"
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        Auth:
          Type: OAUTH
          Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GitHubAccessTokenSecretName}"
      Artifacts:
        Type: S3
        Location: !Ref ArtifactsBucket
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildRoleArn

Outputs:
  CodeBuildProjectName:
    Description: The name of the CodeBuild project
    Value: !Ref CodeBuildProject