AWSTemplateFormatVersion: '2010-09-01'
Description: 'IAM Policies for EKS Components'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  EBSCSIDriverPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AWSEBSCSIDriverPolicy
      Description: Policy for EBS CSI Driver
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateSnapshot
              - ec2:AttachVolume
              - ec2:DetachVolume
              - ec2:ModifyVolume
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeInstances
              - ec2:DescribeSnapshots
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DescribeVolumesModifications
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:CreateTags
            Resource:
              - arn:aws:ec2:*:*:volume/*
              - arn:aws:ec2:*:*:snapshot/*
            Condition:
              StringEquals:
                ec2:CreateAction:
                  - CreateVolume
                  - CreateSnapshot
          - Effect: Allow
            Action:
              - ec2:DeleteTags
            Resource:
              - arn:aws:ec2:*:*:volume/*
              - arn:aws:ec2:*:*:snapshot/*
          - Effect: Allow
            Action:
              - ec2:CreateVolume
            Resource: '*'
            Condition:
              StringLike:
                aws:RequestTag/ebs.csi.aws.com/cluster: 'true'
          - Effect: Allow
            Action:
              - ec2:DeleteVolume
            Resource: '*'
            Condition:
              StringLike:
                ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'

Outputs:
  EBSCSIDriverPolicyArn:
    Description: ARN of the EBS CSI Driver Policy
    Value: !Ref EBSCSIDriverPolicy